name: Deploy Invoice Templates to Production

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Deploy static site to S3 bucket
      run: aws s3 sync --endpoint-url https://s3.nl-ams.scw.cloud ./billboa/public/ s3://billboa-storage-pry2chgz --delete
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: nl-ams
        AWS_REQUEST_CHECKSUM_CALCULATION: WHEN_REQUIRED
        AWS_RESPONSE_CHECKSUM_VALIDATION: WHEN_REQUIRED
